version: 2.1

jobs:
  build:
    docker:
      - image: 'circleci/openjdk:11-jdk'
        environment:
          DB_URL : db_url
          DB_USER : db_user
          DB_PASSWORD : db_paswd
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud